### ISSUE TITLE
incompatible with python 3.6 and 3.7 since 0.0.4

### ISSUE THREAD

**Issue by convoi** [QuiNovas/lambda-pkg-resources#5]
Seems like https://github.com/QuiNovas/lambda-pkg-resources/pull/4/commits/465a577f49ec4e5ab51dc7df5a75a83dfcbe459f#diff-b2cfa2613f4c629d5d2846584c7772a33f1ec893966932b0e2ab609c0915bb18R161
made this incompatible with older python versions. is that intended?
especially nasty since lambda_setuptools does not specify the version of lamdba-pkg-resources and so it automatically pulls it in and breaks

**Comment by joseph-wortmann** [comment]
Quite sorry. I've been writing in 3.8 for so long that I forgot that  ":=" syntax is not available in < 3.8.

I'll fix it and do another push ASAP.

**Comment by joseph-wortmann** [comment]
Just pushed version 0.0.5 that _should_ have made this package work in 3.6/3.7

I don't have an easy way to test those historical releases at the moment, so if you experience another error let me know.
